Document: albumart
Title: Debian albumart Manual
Author: <insert document author here>
Abstract: This manual describes what albumart is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/albumart/albumart.sgml.gz

Format: postscript
Files: /usr/share/doc/albumart/albumart.ps.gz

Format: text
Files: /usr/share/doc/albumart/albumart.text.gz

Format: HTML
Index: /usr/share/doc/albumart/html/index.html
Files: /usr/share/doc/albumart/html/*.html

  
