.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ALBUMART 1 "June  3, 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
albumart-qt \- program for downloading album cover images
.SH SYNOPSIS
.B albumart-qt
.RI [ options ]
.RI [ directory ]
.SH DESCRIPTION
This manual page documents briefly the
.B albumart
program.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBalbumart\fP is a download utility for semi-automatically downloading matching cover images from Amazon.com for each album in your music collection. It saves the cover images so that they will be automatically used by programs such as Konqueror, various XMMS plugins, Windows Media Player, etc.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-d, \-\-download
Download covers for the given path.
.TP
.B \-x, \-\-delete
Remove covers below the given path.
.TP
.B \-s, \-\-synchronize
Synchronizes all covers below the given path.
.TP
.B \-H, \-\-hidden
Don't show a progress dialog while working.
.TP
.B \-i, \-\-summary
Show summary information when done.
.TP
.br
